FROM ubuntu:resolute
LABEL maintainer="Gis3w" Description="This image is used to prepare build requirements for g3w-suite CI testing" Vendor="Gis3w"

ENV DEBIAN_FRONTEND=noninteractive
RUN chown root:root /tmp && chmod ugo+rwXt /tmp
RUN apt-get update && apt install -y \
    git \
    libxml2-dev \
    libxslt-dev \
    libgdal-dev \
    python3-dev \
    libgdal38 \
    python3-gdal \
    python3-pip \
    curl \
    wait-for-it \
    wget \
    vim \
    gdal-bin \
    libsqlite3-mod-spatialite \
    dirmngr \
    xvfb \
    postgresql-client \
    libqt6sql6-psql 

# PyQGIS: set repository
# -------------------------------------------------
RUN curl -L -sS https://download.qgis.org/downloads/qgis-archive-keyring.gpg > /etc/apt/keyrings/qgis-archive-keyring.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] https://qgis.org/ubuntu resolute main" | \
    tee /etc/apt/sources.list.d/qgis.list && \
# Yarn: set repository
# -------------------------------------------------
    curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | \
    gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] \
    https://dl.yarnpkg.com/debian/ stable main" | \
    tee /etc/apt/sources.list.d/yarn.list

# PyQGIS: install
# Yarn: install
# -------------------------------------------------
RUN apt update && apt install -y python3-qgis qgis-server && \
    apt install -y yarn

# PyQGIS: exposes QGIS Python bindings to any Python interpreter
# -------------------------------------------------
ENV PYTHONPATH=/usr/share/qgis/python:${PYTHONPATH}

RUN mkdir /code
WORKDIR /code
