# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='G3WEditingFeatureLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('layer_name', models.CharField(max_length=255)),
                ('layer_datasource', models.TextField(max_length=255)),
                ('sessionid', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_lock_id', models.CharField(db_index=True, max_length=32)),
                ('time_locked', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
