# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='G3WEditingLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
            ],
        ),
    ]
