# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0003_g3weditinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditinglog',
            name='mode',
            field=models.CharField(choices=[(b'add', b'add'), (b'update', b'update'), (b'delete', b'delete')], default=b'add', max_length=10),
        ),
    ]
