# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0004_g3weditinglog_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g3weditinglog',
            name='msg',
            field=models.TextField(),
        ),
    ]
