# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-02 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('qdjango', '0039_merge_20190522_0733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editing', '0005_auto_20181214_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('constraint_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_layer', to='qdjango.Layer')),
                ('editing_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editing_layer', to='qdjango.Layer')),
            ],
            options={
                'verbose_name': 'Layer constraint',
                'managed': True,
                'verbose_name_plural': 'Layer constraints',
            },
        ),
        migrations.CreateModel(
            name='ConstraintRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(max_length=255, verbose_name='SQL WHERE clause for the constraint layer')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editing.Constraint')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constraint rule',
                'verbose_name_plural': 'Constraint rules',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='constraintrule',
            unique_together=set([('constraint', 'user', 'rule'), ('constraint', 'group', 'rule')]),
        ),
    ]
