# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0006_auto_20190802_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditinglayer',
            name='scale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
