# Generated by Django 2.2.9 on 2020-01-31 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0007_g3weditinglayer_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g3weditingfeaturelock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='g3weditinglog',
            name='mode',
            field=models.CharField(choices=[('add', 'add'), ('update', 'update'), ('delete', 'delete')], default='add', max_length=10),
        ),
        migrations.AlterField(
            model_name='g3weditinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
