# Generated by Django 2.2.18 on 2021-03-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0008_auto_20200131_1008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constraintrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='constraintrule',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='constraintrule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='constraintrule',
            name='user',
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.DeleteModel(
            name='ConstraintRule',
        ),
    ]
