# Generated by Django 2.2.27 on 2022-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0009_auto_20210325_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditinglayer',
            name='add_user_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='g3weditinglayer',
            name='edit_user_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
