# Generated by Django 2.2.28 on 2022-06-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0010_auto_20220322_0803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='g3weditinglayer',
            unique_together={('layer_id', 'app_name')},
        ),
    ]
