# Generated by Django 2.2.28 on 2023-02-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0011_auto_20220620_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g3weditinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
