# Generated by Django 3.2.25 on 2024-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0012_auto_20230213_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditinglayer',
            name='visible',
            field=models.BooleanField(blank=True, default=True, help_text='Show layer in layers list to edit', null=True),
        ),
    ]
