# Generated by Django 3.2.25 on 2024-10-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0013_g3weditinglayer_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditinglayer',
            name='add_user_group_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='g3weditinglayer',
            name='edit_user_group_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
