# Generated by Django 3.2.25 on 2024-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0014_auto_20241022_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g3weditinglayer',
            name='add_user_group_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='g3weditinglayer',
            name='edit_user_group_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
