# Generated by Django 4.2.18 on 2025-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0015_auto_20241022_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditinglayer',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
