# Generated by Django 4.2.20 on 2025-03-27 14:08

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0122_auto_20240604_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('run_at', models.CharField(
                    max_length=20,
                    choices=[
                        ('head_start', 'head_start'),
                        ('head_end', 'head_end'),
                        ('body_start', 'body_start'),
                        ('body_end', 'body_end'),
                    ],
                    default='body_end',
                    help_text='Position where the script will be injected.',
                )),
                ('match', models.CharField(
                    max_length=255,
                    default=".*",
                    help_text="Regex pattern to match URLs where the script will run."
                )),
                ('code', models.TextField(default="", blank=True)),
                ('description', models.TextField(
                    default="",
                    blank=True,
                    help_text="Optional description of the userscript."
                )),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        # migrations.RunPython(lambda apps, schema_editor: [
        #     apps.get_model('userscripts', 'UserScript').objects.create(
        #         name="Custom JS",
        #         type="js",
        #         description="A custom JS snippet globally applied."
        #     ),
        #     apps.get_model('userscripts', 'UserScript').objects.create(
        #         name="Custom CSS",
        #         type="css",
        #         run_at='head_end',
        #         description="A custom CSS snippet globally applied."
        #     ),
        #     apps.get_model('userscripts', 'UserScript').objects.create(
        #         name="Custom HTML",
        #         type="xml",
        #         description="A custom HTML snippet globally applied."
        #     ),
        # ]),
    ]
