# Generated by Django 3.2.23 on 2023-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='G3WMapproxyLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.IntegerField()),
                ('baselayer_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
