# Generated by Django 3.2.23 on 2023-12-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0117_auto_20231219_1351'),
        ('mapproxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g3wmapproxylayer',
            name='layer_id',
        ),
        migrations.AddField(
            model_name='g3wmapproxylayer',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qdjango.layer', verbose_name='Cached Layer'),
            preserve_default=False,
        ),
    ]
