# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 11:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersmanage.Department'),
        ),
    ]
