# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_auto_20160224_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='user_avatar', verbose_name='Avatar'),
        ),
    ]
