# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 14:18


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersmanage', '0004_auto_20160321_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userbackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('g3wsuite', 'G3WSUITE'), ('ldap', 'LDAP')], max_length=255, verbose_name='Backend')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
