# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 14:31


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('usersmanage', '0006_userbackend_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], max_length=100, verbose_name='Group role')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='userbackend',
            name='backend',
            field=models.CharField(max_length=255, verbose_name='Backend'),
        ),
    ]
