# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 06:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0007_auto_20180926_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackend',
            name='backend',
            field=models.CharField(choices=[(b'g3wsuite', 'G3WSUITE'), ('ldap', 'LDAP')], default=b'g3wsuite', max_length=255, verbose_name='Backend'),
        ),
    ]
