# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 14:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0008_auto_20190703_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackend',
            name='backend',
            field=models.CharField(choices=[(b'g3wsuite', 'G3WSUITE')], default=b'g3wsuite', max_length=255, verbose_name='Backend'),
        ),
    ]
