# Generated by Django 2.2.16 on 2021-01-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_auto_20191003_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackend',
            name='backend',
            field=models.CharField(choices=[('g3wsuite', 'G3WSUITE')], default='g3wsuite', max_length=255, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usersmanage.Department'),
        ),
    ]
