# Generated by Django 2.2.27 on 2022-04-12 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_auto_20191003_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprole',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='grouprole',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='userbackend',
            name='backend',
            field=models.CharField(choices=[('g3wsuite', 'G3WSUITE')], default='g3wsuite', max_length=255, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usersmanage.Department'),
        ),
    ]
