# Generated by Django 3.2.20 on 2023-09-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0011_auto_20220412_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='Other informations'),
        ),
    ]
