# Generated by Django 3.2.23 on 2023-11-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0013_auto_20230922_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='change_password_first_login',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='User changed password at first login'),
        ),
    ]
