# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qdjango2treeitem',
            name='icon_css_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon css class'),
        ),
    ]
