# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160211_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdjango2treeitem',
            name='type_header',
            field=models.BooleanField(default=False, verbose_name='Tipo header'),
        ),
    ]
