# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupprojectpanoramic'),
    ]

    operations = [
        migrations.CreateModel(
            name='G3WEditingFeatureLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('feature_lock_id', models.CharField(max_length=32)),
                ('time_locked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
