# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_g3weditingfeaturelock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='g3weditingfeaturelock',
            old_name='model',
            new_name='layer_name',
        ),
        migrations.AddField(
            model_name='g3weditingfeaturelock',
            name='layer_datasource',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
