# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 08:07


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20160331_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3weditingfeaturelock',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
