# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 08:13


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_g3weditingfeaturelock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g3weditingfeaturelock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
