# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 08:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160505_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='G3WSpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=256)),
                ('auth_srid', models.IntegerField()),
                ('srtext', models.CharField(max_length=2048)),
                ('proj4text', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('view_group', 'Can view group'),)},
        ),
    ]
