# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 10:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160505_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='units',
        ),
    ]
