# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160527_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselayers',
            options={'verbose_name': 'Base Layer', 'verbose_name_plural': 'Base Layers'},
        ),
        migrations.AddField(
            model_name='group',
            name='baselayers',
            field=models.ManyToManyField(to='core.BaseLayers'),
        ),
    ]
