# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160527_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseLayers',
            new_name='BaseLayer',
        ),
    ]
