# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160527_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='use_commercial_maps',
        ),
        migrations.RemoveField(
            model_name='group',
            name='use_osm_maps',
        ),
    ]
