# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160527_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='baselayers',
            field=models.ManyToManyField(blank=True, null=True, to='core.BaseLayer'),
        ),
    ]
