# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20160609_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
