# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 07:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20160817_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='header_logo_link',
            field=models.URLField(blank=True, help_text='Enter link with http:// or https//', null=True, verbose_name='headerLogoLink'),
        ),
    ]
