# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 09:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20160817_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g3weditingfeaturelock',
            name='user',
        ),
        migrations.DeleteModel(
            name='G3WEditingFeatureLock',
        ),
    ]
