# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 13:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20160823_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='baselayers',
            field=models.ManyToManyField(blank=True, to='core.BaseLayer'),
        ),
        migrations.AlterField(
            model_name='group',
            name='mapcontrols',
            field=models.ManyToManyField(to='core.MapControl'),
        ),
    ]
