# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 08:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20160823_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontrol',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
