# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 08:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_mapcontrol_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcontrol',
            name='order',
        ),
    ]
