# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 15:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20161115_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='panoramic_max_scale',
        ),
        migrations.RemoveField(
            model_name='group',
            name='panoramic_min_scale',
        ),
    ]
