# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 14:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20161219_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_title',
            field=models.CharField(default='G3W-SUITE is a geo suite administration system', max_length=255, verbose_name='About title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_title',
            field=models.CharField(default='Access to backeng administration stystem or logout', max_length=255, verbose_name='Groups title'),
            preserve_default=False,
        ),
    ]
