# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 15:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20161222_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='header_logo_img',
            field=models.FileField(upload_to='logo_img', verbose_name='Logo image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='header_logo_link',
            field=models.URLField(blank=True, help_text='Enter link with http:// or https//', null=True, verbose_name='Logo link'),
        ),
    ]
