# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20161222_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='flickr_url',
            field=models.URLField(blank=True, null=True, verbose_name='Flickr link'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='tripadvisor_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tripadvisor link'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube link'),
        ),
    ]
