# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 11:59


from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_group_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo_img', models.FileField(upload_to='macrogroup/logo_img', verbose_name='Logo image')),
                ('logo_link', models.URLField(blank=True, help_text='Enter link with http:// or https//', null=True, verbose_name='Logo link')),
                ('groups', models.ManyToManyField(to='core.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
