# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 12:15


from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_macrogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrogroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(default=None, editable=False, unique=True, populate_from=['title'],verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
