# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 12:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_macrogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrogroup',
            name='slug',
            field=models.SlugField(default=None, editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
