# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 12:15


import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_macrogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrogroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='title', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
