# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 16:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20171028_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrogroup',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='macrogroups',
            field=models.ManyToManyField(blank=True, to='core.MacroGroup'),
        ),
    ]
