# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 10:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20171031_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='url_suite_logo',
            field=models.URLField(blank=True, null=True, verbose_name='Suite logo URL'),
        ),
    ]
