# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 07:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20181002_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='credits',
            field=models.TextField(blank=True, null=True, verbose_name='Credits'),
        ),
    ]
