# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 08:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_generalsuitedata_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
