# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 16:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_baselayer_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMapUrlAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('layer_id', models.IntegerField()),
                ('alias', models.CharField(max_length=512)),
            ],
        ),
    ]
