# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 16:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_projectmapurlalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmapurlalias',
            name='alias',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
