# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 17:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20190304_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmapurlalias',
            old_name='layer_id',
            new_name='project_id',
        ),
    ]
