# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20190304_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('view_group', 'Can view group'), ('add_project_to_group', 'Can add view proejct to the group'))},
        ),
    ]
