# Generated by Django 2.2.9 on 2020-01-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20191230_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('add_project_to_group', 'Can add project to the group'),)},
        ),
    ]
