# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20191219_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('view_group', 'Can view group'), ('add_project_to_group', 'Can add project to the group'))},
        ),
    ]
