# Generated by Django 2.2.9 on 2020-03-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200302_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_it',
        ),
    ]
