# Generated by Django 2.2.9 on 2020-03-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200302_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrogroup',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='macrogroup',
            name='title_it',
        ),
    ]
