# Generated by Django 2.2.9 on 2020-03-11 10:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_macrogroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrogroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
    ]
