# Generated by Django 2.2.9 on 2020-03-11 10:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_macrogroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrogroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
