# Generated by Django 2.2.9 on 2020-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_macrogroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrogroup',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
