# Generated by Django 2.2.10 on 2020-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200311_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrogroup',
            name='use_title_logo_client',
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='use_logo_client',
            field=models.BooleanField(default=False, verbose_name='Use logo image for client'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='use_title_client',
            field=models.BooleanField(default=False, verbose_name='Use title for client'),
        ),
    ]
