# Generated by Django 2.2.16 on 2021-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20210110_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
