# Generated by Django 2.2.16 on 2021-02-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20210111_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselayer',
            options={'ordering': ('order',), 'verbose_name': 'Base Layer', 'verbose_name_plural': 'Base Layers'},
        ),
    ]
