# Generated by Django 2.2.16 on 2021-03-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210309_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='use_title_client',
        ),
    ]
