# Generated by Django 3.2.13 on 2022-04-21 12:09

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20220308_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='about_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='about_name_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='about_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='credits_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='groups_map_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='groups_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='home_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='login_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='main_map_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='sub_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='group',
            name='header_terms_of_use_text_de',
        ),
        migrations.RemoveField(
            model_name='group',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='macrogroup',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='macrogroup',
            name='title_de',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='macrogroup',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
