# Generated by Django 2.2.27 on 2022-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20220308_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='about_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='about_name_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='about_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='credits_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='groups_map_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='groups_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='home_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='login_description_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='main_map_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='sub_title_de',
        ),
        migrations.RemoveField(
            model_name='generalsuitedata',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='group',
            name='header_terms_of_use_text_de',
        ),
        migrations.RemoveField(
            model_name='group',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='macrogroup',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='macrogroup',
            name='title_de',
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
    ]
