# Generated by Django 2.2.27 on 2022-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20220428_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_fi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_se',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
    ]
