# Generated by Django 2.2.27 on 2022-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20220428_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='About description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_name_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='About name'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='credits_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_map_description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Groups map description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Groups title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='home_description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Home description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Login description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_ro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='main_map_title_ro',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main map title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='sub_title_ro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='header_terms_of_use_text_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of use text'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
