# Generated by Django 2.2.27 on 2022-05-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20220502_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='About description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='About name'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='credits_de',
            field=models.TextField(blank=True, null=True, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_map_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Groups map description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Groups title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='home_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Home description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Login description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='main_map_title_de',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main map title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='sub_title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='header_terms_of_use_text_de',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of use text'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
