# Generated by Django 2.2.28 on 2023-03-29 07:39

from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_statuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='header_logo_img',
            field=models.FileField(default=f'logo_img/{settings.CLIENT_G3WSUITE_LOGO}', upload_to='logo_img', verbose_name='Logo image'),
        ),
    ]
