# Generated by Django 3.2.20 on 2023-09-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20230329_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
    ]
