# Generated by Django 3.2.20 on 2023-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_generalsuitedata_registration_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_de',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_it',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_se',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
    ]
