# Generated by Django 4.2.18 on 2025-04-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20230921_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('order',), 'permissions': (('add_project_to_group', 'Can add project to the group'),)},
        ),
        migrations.AlterModelOptions(
            name='macrogroup',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='g3w2treeitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent site tree item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_parent', to='core.g3w2treeitem', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='g3w2treeitem',
            name='tree',
            field=models.ForeignKey(help_text='Site tree this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tree', to='core.g3w2tree', verbose_name='Site Tree'),
        ),
    ]
