# Generated by Django 4.2.18 on 2025-05-16 10:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_shorturl_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermaLinkURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data', models.JSONField()),
                ('short_code', models.CharField(blank=True, max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
