# Generated by Django 4.2.18 on 2025-05-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_permalinkurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permalinkurl',
            old_name='short_code',
            new_name='permlink_code',
        ),
    ]
