# Generated by Django 4.2.18 on 2025-05-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_rename_short_code_permalinkurl_permlink_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permalinkurl',
            old_name='permlink_code',
            new_name='permalink_code',
        ),
    ]
