# Generated by Django 4.2.21 on 2025-07-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_rename_permlink_code_permalinkurl_permalink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='group',
            name='baselayers',
            field=models.ManyToManyField(blank=True, to='core.baselayer', verbose_name='Base layers'),
        ),
        migrations.AlterField(
            model_name='group',
            name='macrogroups',
            field=models.ManyToManyField(blank=True, to='core.macrogroup', verbose_name='MACRO groups'),
        ),
        migrations.AlterField(
            model_name='group',
            name='mapcontrols',
            field=models.ManyToManyField(to='core.mapcontrol', verbose_name='Map controls'),
        ),
        migrations.AlterField(
            model_name='group',
            name='srid',
            field=models.ForeignKey(db_column='srid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.g3wspatialrefsys', verbose_name='SRID'),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('order',), 'permissions': (('add_project_to_group', 'Can add project to the group'),), 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='macrogroup',
            options={'ordering': ('order',), 'verbose_name': 'MACRO Group', 'verbose_name_plural': 'MACRO Groups'},
        ),
    ]
