# Generated by Django 4.2.21 on 2025-07-06 22:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_rename_permlink_code_permalinkurl_permalink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=core.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='macrogroup',
            name='slug',
            field=core.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
    ]
