# Generated by Django 4.2.21 on 2025-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_add_verbose_names_and_nothing_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselayer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='property',
            field=models.TextField(verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='g3w2tree',
            name='module',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qdjango2 module'),
        ),
        migrations.AlterField(
            model_name='g3w2treeitem',
            name='icon_css_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon CSS class'),
        ),
        migrations.AlterField(
            model_name='g3w2treeitem',
            name='type_header',
            field=models.BooleanField(blank=True, default=False, verbose_name='Type header'),
        ),
        migrations.AlterField(
            model_name='g3wspatialrefsys',
            name='auth_name',
            field=models.CharField(max_length=256, verbose_name='SRS name'),
        ),
        migrations.AlterField(
            model_name='g3wspatialrefsys',
            name='auth_srid',
            field=models.IntegerField(verbose_name='SRS ID'),
        ),
        migrations.AlterField(
            model_name='g3wspatialrefsys',
            name='proj4text',
            field=models.CharField(max_length=2048, verbose_name='PROJ coordinate definition'),
        ),
        migrations.AlterField(
            model_name='g3wspatialrefsys',
            name='srid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='SRID'),
        ),
        migrations.AlterField(
            model_name='g3wspatialrefsys',
            name='srtext',
            field=models.CharField(max_length=2048, verbose_name='WKT SRS'),
        ),
        migrations.AlterField(
            model_name='mapcontrol',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mapcontrol',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectmapurlalias',
            name='alias',
            field=models.CharField(max_length=512, unique=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='projectmapurlalias',
            name='app_name',
            field=models.CharField(max_length=255, verbose_name='App name'),
        ),
        migrations.AlterField(
            model_name='projectmapurlalias',
            name='project_id',
            field=models.IntegerField(verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], db_index=True, default=40, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='logger_name',
            field=models.CharField(max_length=100, verbose_name='Logger name'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='msg',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='trace',
            field=models.TextField(blank=True, null=True, verbose_name='Trace'),
        ),
        migrations.AlterField(
            model_name='permalinkurl',
            name='data',
            field=models.JSONField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='permalinkurl',
            name='permalink_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Permalink code'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=2000, verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Short code'),
        ),
    ]
