# Generated by Django 4.2.22 on 2025-07-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_group_slug_alter_macrogroup_slug'),
        ('core', '0091_add_verbose_names_and_nothing_more_v2'),
    ]

    operations = [
    ]
