# Generated by Django 4.2.21 on 2025-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_merge_20250708_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='About description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_name_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='About name'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='about_title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='About title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='credits_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_map_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Groups map description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='groups_title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Groups title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='home_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Home description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Login description'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='login_title_bg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Login title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='main_map_title_bg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Main map title'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='registration_intro_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Registration introductory message'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='sub_title_bg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='generalsuitedata',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='header_terms_of_use_text_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Terms of use text'),
        ),
        migrations.AddField(
            model_name='group',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='macrogroup',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
