# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 16:20
from __future__ import unicode_literals

import autoslug.fields
import cdu.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0013_layer_tilestache_conf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('odtfile', models.FileField(null=True, upload_to=cdu.models.getOdtfilePath, verbose_name='ODT Template file')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from=b'title', unique=True, verbose_name='Slug')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Project')),
            ],
            options={
                'permissions': (('make_cdu', 'Can make CDU analisys'), ('view_configs', 'Can view configs')),
            },
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=300, null=True)),
                ('fields', models.TextField()),
                ('catasto', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdu.Configs')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Layer')),
            ],
        ),
    ]
