name: 🐞 Bug report
description: Report a bug/issue
labels: [bug]
assignees: [wlorenzetti]
body:
- type: checkboxes
  attributes:
    label: Checklist
    description: >
      Please confirm the following:
    options:
    - label: I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before
      required: false
- type: textarea
  attributes:
    label: Subject of the issue
    description: Describe your issue here.
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
     Please provide as much information as possible in order to resolve your issue. Need help? [Find out your version](https://github.com/g3w-suite/g3w-admin#version).
    value: |
     - g3w-admin: __version__
     - g3w-client: __version__
     - browser: __name__
     - operating system: __name and version (desktop or mobile)__
  validations:
    required: true
- type: input
  attributes:
    label: Link to your project
    description: A public URL that can help others to check your issue
    placeholder: eg. https://dev.g3wsuite.it/en/map/demo-34/
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional info
    description: |
      Add any other useful information that could allow others to replicate your issue, for example:
      - **installed plugins**
      - **project structure**
      - **configuration files**
      - **self-explanatory pictures**
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
