name: ☝️ Feature request
description: Suggest an idea for this project
labels: 'feature'
assignees: [wlorenzetti]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please confirm the following:
      options:
        - label: I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.
          required: false

  - type: textarea
    attributes:
      label: Motivation
      description: Is your feature request related to a problem? Provide a clear and concise description of what the problem is.
      placeholder: e.g. "I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested solution
      description: Provide a clear and concise description of what you want to happen.
      placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Please describe any alternative solutions or features you've considered.
      placeholder: Screenshots, video, links, etc.
    validations:
      required: false
