name: 📄 Improve documentation
description: Suggest new additions or updates to existing documentation
labels: 'docs'
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please confirm the following:
      options:
        - label: I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.
          required: false

  - type: input
    attributes:
      label: Which documents need updating?
      description: >
        For existing content, please provide one or more URLs of documents that need updating.
        You may also provide [permalinks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) to the relevant source code.
      placeholder: e.g. "https://g3w-suite.readthedocs.io/en/v.3.4.x/g3wsuite_administration.html"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Motivation
      description: Why is this change needed? Provide a clear and concise description of what the problem is.
      placeholder: >
        e.g. "The documentation doesn't help me understand how to [...]"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested changes
      description: Provide a clear and concise description of the changes you want to see.
      placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
