FROM ubuntu:16.04
MAINTAINER Walter Lorenzetti<lorenzetti@gis3w.it>

RUN  apt-get update && apt-get dist-upgrade -y

RUN  apt-get install -y \
	git \
	python-pip \
	software-properties-common \
	xvfb \
	supervisor \
	nginx \
	fcgiwrap


RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
COPY apt-qgis.list /etc/apt/sources.list.d/
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key 073D307A618E5811
RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y \
    libxml2-dev \
    libxslt-dev \
    postgressql-9.5-postgis-2.3 \
    postgresql-server-dev-all \
    libgdal-dev \
    qgis-server

RUN mkdir /home/g3wsuite
RUN mkdir /home/g3wsuite/www
RUN mkdir /home/g3wsuite/www/static
RUN mkdir /home/g3wsuite/www/media
RUN mkdir /home/g3wsuite/cache
RUN mkdir /home/g3wsuite/log


COPY requirements.txt /home/g3wsuite/
WORKDIR /home/g3wsuite
RUN pip install -r requirements.txt

# install python-gdal
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

RUN pip install GDAL==2.1.3





