FROM gis3w/g3wsuite-base:latest
MAINTAINER Walter Lorenzetti<lorenzetti@gis3w.it>

WORKDIR /home/g3wsuite

RUN git clone https://wlorenzetti:kotegaeshi7890@bitbucket.org/gis3w/g3w-admin.git

COPY install-modules.sh /home/g3wsuite/g3w-admin/
RUN chmod +x /home/g3wsuite/g3w-admin/install-modules.sh
WORKDIR /home/g3wsuite/g3w-admin
RUN ./install-modules.sh

# install bower
RUN apt-get install -y nodejs-legacy npm
RUN npm install -g bower
RUN bower --allow-root install






