# Generated by Django 2.2.23 on 2021-11-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0082_auto_20210819_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRasterTimeSeriesLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Layer')),
            ],
        ),
    ]
