# Generated by Django 2.2.23 on 2021-11-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtimeseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrastertimeserieslayer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrastertimeserieslayer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
