# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:31


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qdjango_projetc_group', to='core.Group', verbose_name='Group'),
        ),
    ]
