# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 08:19


from django.db import migrations, models
import django.db.models.deletion
import qdjango.models
import qdjango.utils.storage
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0002_auto_20160303_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(editable=False, unique=True, populate_from=['name'], verbose_name='Slug')),
                ('is_active', models.BooleanField(default=1, verbose_name='Is active')),
                ('layer_type', models.CharField(choices=[(b'postgres', 'Postgres'), (b'spatialite', 'SpatiaLite'), (b'wfs', 'WFS'), (b'wms', 'WMS'), (b'ogr', 'OGR'), (b'gdal', 'GDAL')], max_length=255, verbose_name='Type')),
                ('datasource', models.TextField(verbose_name='Datasource')),
                ('is_visible', models.BooleanField(default=1, verbose_name='Is visible')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('data_file', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Associated data file')),
                ('database_columns', models.TextField(blank=True, verbose_name='Database columns')),
            ],
            options={
                'ordering': ['order'],
                'permissions': (('view_layer', 'Can view layer'),),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qdjango_project_group', to='core.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='qgis_file',
            field=models.FileField(storage=qdjango.utils.storage.QgisFileOverwriteStorage(), upload_to=qdjango.models.get_project_file_path, verbose_name='QGIS project file'),
        ),
        migrations.AddField(
            model_name='layer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Project', verbose_name='Project'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set([('name', 'project')]),
        ),
    ]
