# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 14:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0003_auto_20160310_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
