# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 08:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0004_auto_20160314_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qdjango_project', to='core.Group', verbose_name='Group'),
        ),
    ]
