# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 11:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0006_project_layers_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='qgs_layer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qgis Layer Porject ID'),
        ),
    ]
