# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 10:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0007_layer_qgs_layer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='max_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Layer Max Scale visibility'),
        ),
        migrations.AddField(
            model_name='layer',
            name='min_scale',
            field=models.FloatField(blank=True, null=True, verbose_name='Layer Min Scale visibility'),
        ),
        migrations.AddField(
            model_name='layer',
            name='scalebasedvisibility',
            field=models.BooleanField(default=False, verbose_name='Layer scale based visibility'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=b'/home/www/django-qgis-static/media/data/', verbose_name='Associated data file'),
        ),
    ]
