# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0009_auto_20160317_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='srid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Layer SRID'),
        ),
    ]
