# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0010_layer_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='capabilities',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitwise capabilities'),
        ),
        migrations.AddField(
            model_name='layer',
            name='edit_options',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitwise edit options'),
        ),
    ]
