# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 15:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0011_auto_20160317_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_panoramic_map',
        ),
    ]
