# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0012_remove_project_is_panoramic_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='tilestache_conf',
            field=models.TextField(blank=True, null=True, verbose_name='Tilestache layer configurations paramenters'),
        ),
    ]
