# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 14:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0013_layer_tilestache_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='geomentrytype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Geometry type'),
        ),
    ]
