# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 15:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0014_layer_geomentrytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='geomentrytype',
            new_name='geometrytype',
        ),
    ]
