# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 14:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0015_auto_20160415_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='database_columns',
            field=models.TextField(blank=True, null=True, verbose_name='Database columns'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[(b'postgres', 'Postgres'), (b'spatialite', 'SpatiaLite'), (b'raster', 'Raster'), (b'wfs', 'WFS'), (b'wms', 'WMS'), (b'ogr', 'OGR'), (b'gdal', 'GDAL')], max_length=255, verbose_name='Type'),
        ),
    ]
