# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 08:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0016_auto_20160420_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['order'], 'permissions': (('view_qdjango_layer', 'Can view qdjango layer'), ('add_qdjango_layer', 'Can add qdjango layer'), ('change_qdjango_layer', 'Can change qdjango layer'), ('delete_qdjango_layer', 'Can delete qdjango layer'))},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_qdjango_project', 'Can view qdjango project'), ('add_qdjango_project', 'Can add qdjango project'), ('change_qdjango_project', 'Can change qdjango project'), ('delete_qdjango_project', 'Can delete qdjango project'))},
        ),
    ]
