# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 09:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0017_auto_20160502_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['order'], 'permissions': (('view_layer', 'Can view qdjango layer'),)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'Can view qdjango project'),)},
        ),
    ]
