# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 07:41


import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0018_auto_20160502_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('body', models.TextField(verbose_name='Body')),
                ('datasource', models.TextField(verbose_name='datasource')),
                ('widget_type', models.CharField(choices=[(b'search', 'Search'), (b'tooltip', 'Tooltip'), (b'law', 'Law')], max_length=255, verbose_name='Type')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=b'name', unique=True, verbose_name='Slug')),
                ('layers', models.ManyToManyField(to='qdjango.Layer')),
            ],
            options={
                'permissions': (('view_widget', 'Can view widget'),),
            },
        ),
    ]
