# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:52


from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160530_0740'),
        ('qdjango', '0020_auto_20160509_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='baselayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BaseLayer', verbose_name='Base Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='/home/www/django-qgis-static/media/data/', verbose_name='Associated data file'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('spatialite', 'SpatiaLite'), ('raster', 'Raster'), ('wfs', 'WFS'), ('wms', 'WMS'), ('ogr', 'OGR'), ('gdal', 'GDAL')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(editable=False, unique=True, verbose_name='Slug', populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='project',
            name='qgis_version',
            field=models.CharField(default='', max_length=255, verbose_name='Qgis project version'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(editable=False, unique=True, verbose_name='Slug', populate_from=['title']),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search'), ('tooltip', 'Tooltip'), ('law', 'Law')], max_length=255, verbose_name='Type'),
        ),
    ]
