# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0022_auto_20160530_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[(b'search', 'Search'), (b'law', 'Law'), (b'tooltip', 'Tooltip')], max_length=255, verbose_name='Type'),
        ),
    ]
