# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 13:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0023_auto_20160711_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='origname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Original Name'),
        ),
    ]
