# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 15:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0024_layer_origname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set([('name', 'project', 'qgs_layer_id')]),
        ),
    ]
