# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 15:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0025_auto_20160816_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_extent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Max extent'),
        ),
    ]
