# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 15:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0027_layer_wfscapabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='relations',
            field=models.TextField(blank=True, null=True, verbose_name='Layer relations'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[(b'search', 'Search'), (b'law', 'Law')], max_length=255, verbose_name='Type'),
        ),
    ]
