# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-23 08:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0028_auto_20170214_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='exclude_attribute_wfs',
            field=models.TextField(blank=True, null=True, verbose_name='Attributes excluded from wfs'),
        ),
        migrations.AddField(
            model_name='layer',
            name='exclude_attribute_wms',
            field=models.TextField(blank=True, null=True, verbose_name='Attributes excluded from wms'),
        ),
    ]
