# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0030_auto_20170818_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='edittypes',
            field=models.TextField(blank=True, null=True, verbose_name='Columns layer widgets'),
        ),
    ]
