# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 16:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0032_layer_exlude_from_legend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='exlude_from_legend',
            new_name='exclude_from_legend',
        ),
    ]
