# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-22 08:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0033_auto_20171229_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='editor_form_structure',
            field=models.TextField(blank=True, null=True, verbose_name='Editor form structure'),
        ),
        migrations.AddField(
            model_name='layer',
            name='editor_layout',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form editor layout'),
        ),
    ]
