# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 08:24


from django.db import migrations, models
import qdjango.models
import qdjango.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0034_auto_20180822_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='qgis_file',
            field=models.FileField(max_length=400, storage=qdjango.utils.storage.QgisFileOverwriteStorage(), upload_to=qdjango.models.get_project_file_path, verbose_name='QGIS project file'),
        ),
    ]
