# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 10:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0037_auto_20190114_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wms_use_layer_ids',
            field=models.BooleanField(default=False, verbose_name='WMS use layer ids'),
        ),
    ]
