# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 13:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0037_project_wms_use_layer_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature_count_wms',
            field=models.IntegerField(default=5, verbose_name='Max feature to get for query'),
        ),
        migrations.AddField(
            model_name='project',
            name='multilayer_query',
            field=models.CharField(choices=[(b'single', 'Single'), (b'multiple', 'Multiple')], default=b'single', max_length=20, verbose_name='Query control mode'),
        ),
        migrations.AddField(
            model_name='project',
            name='multilayer_querybybbox',
            field=models.CharField(choices=[(b'single', 'Single'), (b'multiple', 'Multiple')], default=b'single', max_length=20, verbose_name='Query by bbox control mode'),
        ),
        migrations.AddField(
            model_name='project',
            name='multilayer_querybypolygon',
            field=models.CharField(choices=[(b'single', 'Single'), (b'multiple', 'Multiple')], default=b'single', max_length=20, verbose_name='Query by polygon control mode'),
        ),
    ]
