# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-22 07:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0037_auto_20190114_0815'),
        ('qdjango', '0038_auto_20190315_1344'),
    ]

    operations = [
    ]
