# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-09 14:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0039_merge_20190522_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[(b'postgres', 'Postgres'), (b'spatialite', 'SpatiaLite'), (b'raster', 'Raster'), (b'wfs', 'WFS'), (b'wms', 'WMS'), (b'ogr', 'OGR'), (b'gdal', 'GDAL'), (b'delimitedtext', 'CSV'), (b'arcgismapserver', 'ArcGisMapServer'), (b'arcgisfeatureserver', 'ArcGisFeatureServer')], max_length=255, verbose_name='Type'),
        )
    ]
