# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-26 16:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0040_auto_20190809_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[(b'search', 'Search'), (b'law', 'Law')], max_length=255, verbose_name='Type'),
        ),
    ]
