# Generated by Django 2.2.9 on 2019-12-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0042_layer_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['order'], 'verbose_name': 'Layer', 'verbose_name_plural': 'Layers'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={},
        ),
        migrations.AlterField(
            model_name='layer',
            name='download',
            field=models.BooleanField(blank=True, default=False, verbose_name='Download data'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='exclude_from_legend',
            field=models.BooleanField(blank=True, default=False, verbose_name='Exclude to legend'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='external',
            field=models.BooleanField(blank=True, default=False, verbose_name='Get WMS/WMS externally'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('spatialite', 'SpatiaLite'), ('raster', 'Raster'), ('wfs', 'WFS'), ('wms', 'WMS'), ('ogr', 'OGR'), ('gdal', 'GDAL'), ('delimitedtext', 'CSV'), ('arcgismapserver', 'ArcGisMapServer'), ('arcgisfeatureserver', 'ArcGisFeatureServer')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='baselayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qdjango_project_baselayer', to='core.BaseLayer', verbose_name='Base Layer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qdjango_project', to='core.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='multilayer_query',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20, verbose_name='Query control mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='multilayer_querybybbox',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20, verbose_name='Query by bbox control mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='multilayer_querybypolygon',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20, verbose_name='Query by polygon control mode'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search')], max_length=255, verbose_name='Type'),
        ),
    ]
