# Generated by Django 2.2.9 on 2020-01-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0043_auto_20191230_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search'), ('law', 'Law')], max_length=255, verbose_name='Type'),
        ),
    ]
