# Generated by Django 2.2.9 on 2020-04-15 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qdjango', '0043_auto_20191230_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constrainted_layer', to='qdjango.Layer')),
            ],
            options={
                'verbose_name': 'Layer constraint',
                'verbose_name_plural': 'Layer constraints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstraintRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(max_length=255, verbose_name='SQL WHERE clause for the constraint layer')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Constraint')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constrainted_rule_group', to='auth.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constrainted_rule_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constraint rule',
                'verbose_name_plural': 'Constraint rules',
                'managed': True,
                'unique_together': {('constraint', 'group', 'rule'), ('constraint', 'user', 'rule')},
            },
        ),
    ]
