# Generated by Django 2.2.9 on 2020-04-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qdjango', '0044_auto_20200131_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search')], max_length=255, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='SingleLayerConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constrainted_layer', to='qdjango.Layer')),
            ],
            options={
                'verbose_name': 'Layer constraint',
                'verbose_name_plural': 'Layer constraints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstraintSubsetStringRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='Definition of the rule, either an SQL WHERE condition or a QgsExpression definition depending on the rule type', max_length=1024, verbose_name='Rule definition')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.SingleLayerConstraint')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constraint subset string rule',
                'verbose_name_plural': 'Constraint subset string rules',
                'abstract': False,
                'managed': True,
                'unique_together': {('constraint', 'group', 'rule'), ('constraint', 'user', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='ConstraintExpressionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='Definition of the rule, either an SQL WHERE condition or a QgsExpression definition depending on the rule type', max_length=1024, verbose_name='Rule definition')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.SingleLayerConstraint')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constraint expression rule',
                'verbose_name_plural': 'Constraint expression rules',
                'abstract': False,
                'managed': True,
                'unique_together': {('constraint', 'group', 'rule'), ('constraint', 'user', 'rule')},
            },
        ),
    ]
