# Generated by Django 2.2.10 on 2020-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0045_auto_20200421_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('spatialite', 'SpatiaLite'), ('raster', 'Raster'), ('wfs', 'WFS'), ('wms', 'WMS'), ('ogr', 'OGR'), ('gdal', 'GDAL'), ('delimitedtext', 'CSV'), ('arcgismapserver', 'ArcGisMapServer'), ('arcgisfeatureserver', 'ArcGisFeatureServer'), ('mssql', 'MSSQL')], max_length=255, verbose_name='Type'),
        ),
    ]
