# Generated by Django 2.2.9 on 2020-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0045_auto_20200302_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
    ]
