# Generated by Django 2.2.10 on 2020-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0046_auto_20200504_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlelayerconstraint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='singlelayerconstraint',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
