# Generated by Django 2.2.9 on 2020-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0046_project_title_ur'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_ur_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
    ]
