# Generated by Django 2.2.10 on 2020-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0047_auto_20200505_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='download_xls',
            field=models.BooleanField(blank=True, default=False, verbose_name='Download data in xls format'),
        ),
    ]
