# Generated by Django 2.2.9 on 2020-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0044_constraint_constraintrule'),
        ('qdjango', '0047_auto_20200401_0908'),
    ]

    operations = [
    ]
