# Generated by Django 2.2.13 on 2020-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0048_layer_download_xls'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='download_gpx',
            field=models.BooleanField(blank=True, default=False, verbose_name='Download data in gpx format'),
        ),
    ]
