# Generated by Django 2.2.13 on 2020-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0049_layer_download_gpx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('spatialite', 'SpatiaLite'), ('raster', 'Raster'), ('wfs', 'WFS'), ('wms', 'WMS'), ('ogr', 'OGR'), ('gdal', 'GDAL'), ('delimitedtext', 'CSV'), ('arcgismapserver', 'ArcGisMapServer'), ('arcgisfeatureserver', 'ArcGisFeatureServer'), ('mssql', 'MSSQL'), ('virtual', 'VirtualLayer')], max_length=255, verbose_name='Type'),
        ),
    ]
