# Generated by Django 2.2.13 on 2020-10-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0053_layer_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context_base_legend',
            field=models.BooleanField(default=False, help_text='Show only the symbols for the features falling into the requested area', verbose_name='Context base legend'),
        ),
    ]
