# Generated by Django 2.2.16 on 2021-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0057_auto_20201210_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisAuth',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='QgisAuth ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('uri', models.TextField(blank=True, null=True, verbose_name='URI (unused)')),
                ('type', models.TextField(default='Basic', verbose_name='Type')),
                ('version', models.IntegerField(default=2, verbose_name='Version')),
                ('config', models.TextField(verbose_name='Config')),
            ],
            options={
                'verbose_name': 'QgisAuth',
                'verbose_name_plural': 'QgisAuths',
            },
        ),
    ]
