# Generated by Django 2.2.16 on 2021-01-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0058_qgisauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qgisauth',
            old_name='type',
            new_name='config_type',
        ),
    ]
