# Generated by Django 2.2.16 on 2020-12-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0058_singlelayersessionfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlelayersessionfilter',
            name='token',
            field=models.CharField(max_length=54),
        ),
    ]
