# Generated by Django 2.2.16 on 2021-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0059_auto_20210104_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qgisauth',
            name='config_type',
        ),
        migrations.AddField(
            model_name='qgisauth',
            name='method',
            field=models.TextField(default='Basic', verbose_name='Method'),
        ),
    ]
