# Generated by Django 2.2.16 on 2021-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0059_auto_20201231_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlelayersessionfilter',
            name='sessionid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
