# Generated by Django 2.2.16 on 2021-01-04 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qdjango', '0060_auto_20210104_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlelayersessionfilter',
            name='sessionid',
        ),
        migrations.RemoveField(
            model_name='singlelayersessionfilter',
            name='time_asked',
        ),
        migrations.RemoveField(
            model_name='singlelayersessionfilter',
            name='token',
        ),
        migrations.RemoveField(
            model_name='singlelayersessionfilter',
            name='user',
        ),
        migrations.CreateModel(
            name='SessionTokenFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=54)),
                ('time_asked', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='singlelayersessionfilter',
            name='session_token_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.SessionTokenFilter'),
            preserve_default=False,
        ),
    ]
