# Generated by Django 2.2.16 on 2021-01-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0063_auto_20210111_0726'),
        ('qdjango', '0061_auto_20210104_1458'),
    ]

    operations = [
    ]
