# Generated by Django 2.2.16 on 2021-01-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0064_layer_download_gpkg'),
        ('qdjango', '0064_merge_20210111_1641'),
    ]

    operations = [
    ]
