# Generated by Django 2.2.16 on 2021-03-08 09:40

import django.core.validators
from django.db import migrations, models
import qdjango.models.qgisauth


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0065_merge_20210113_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qgisauth',
            options={'verbose_name': 'QGIS Authentication', 'verbose_name_plural': 'QGIS Authentications'},
        ),
        migrations.AddField(
            model_name='project',
            name='toc_tab_default',
            field=models.CharField(choices=[('layers', 'Layers'), ('baselayers', 'Base layers'), ('legend', 'Legend')], default='layers', help_text='Set TOC tab open by default on loading map', max_length=40, verbose_name='Tab of TOC active as default'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('spatialite', 'SpatiaLite'), ('raster', 'Raster'), ('wfs', 'WFS'), ('wms', 'WMS'), ('ogr', 'OGR'), ('gdal', 'GDAL'), ('delimitedtext', 'CSV'), ('arcgismapserver', 'ArcGisMapServer'), ('arcgisfeatureserver', 'ArcGisFeatureServer'), ('mssql', 'MSSQL'), ('virtual', 'VirtualLayer'), ('oracle', 'Oracle'), ('vector-tile', 'Vector Tile')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='qgisauth',
            name='config',
            field=models.TextField(default="{'password': '<your_password>', 'username': '<your_username>', 'realm': ''}", help_text='Fill in username and passwword, realm is not implemented and it can be left blank', verbose_name='Config'),
        ),
        migrations.AlterField(
            model_name='qgisauth',
            name='id',
            field=models.CharField(default=qdjango.models.qgisauth.default_authid, help_text='7 alphanumeric ASCII chars', max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[A-z0-9]{7}')], verbose_name='Auth ID'),
        ),
        migrations.AlterField(
            model_name='qgisauth',
            name='method',
            field=models.CharField(default='Basic', editable=False, max_length=32, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='qgisauth',
            name='uri',
            field=models.CharField(blank=True, help_text='Currently not implemented', max_length=256, null=True, verbose_name='URI'),
        ),
    ]
