# Generated by Django 2.2.16 on 2021-03-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0066_auto_20210308_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='toc_tab_default',
            field=models.CharField(choices=[('layers', 'Layers'), ('baselayers', 'Base layers'), ('legend', 'Legend')], default='layers', help_text="Set tab's TOC open by default on init client", max_length=40, verbose_name="Tab's TOC active as default"),
        ),
    ]
