# Generated by Django 2.2.16 on 2021-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0070_auto_20210312_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlelayerconstraint',
            name='for_view',
            field=models.BooleanField(default=True, help_text='Active this constraint for users have viewing grant on layer/project', null=True, verbose_name='Active for visualization'),
        ),
    ]
