# Generated by Django 2.2.16 on 2021-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0071_auto_20210312_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_dirty',
            field=models.BooleanField(default=False, editable=False, verbose_name='The project has been modified by the G3W-Suite application after it was uploaded.'),
        ),
    ]
