# Generated by Django 2.2.16 on 2021-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0072_project_is_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_locked',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mutex to lock the project when it is being written by the G3W-Suite application. This field is used internally by the suite through a context manager'),
        ),
    ]
