# Generated by Django 2.2.18 on 2021-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0074_geoconstraint_geoconstraintrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoconstraint',
            name='for_editing',
            field=models.BooleanField(default=False, help_text='Active this constraint for users have editing grant on layer/project', null=True, verbose_name='Active for editing'),
        ),
        migrations.AddField(
            model_name='geoconstraint',
            name='for_view',
            field=models.BooleanField(default=True, help_text='Active this constraint for users have viewing grant on layer/project', null=True, verbose_name='Active for visualization'),
        ),
    ]
