# Generated by Django 2.2.18 on 2021-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0075_auto_20210325_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoconstraint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
