# Generated by Django 2.2.23 on 2021-07-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0076_geoconstraint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='not_show_attributes_table',
            field=models.BooleanField(blank=True, default=False, verbose_name='Not show attributes table'),
        ),
    ]
