# Generated by Django 2.2.23 on 2021-07-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0078_auto_20210708_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoconstraintrule',
            name='anonymoususer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
