# Generated by Django 2.2.23 on 2021-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0077_layer_not_show_attributes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
    ]
