# Generated by Django 2.2.23 on 2021-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0078_geoconstraintrule_anonymoususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraintexpressionrule',
            name='anonymoususer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='constraintsubsetstringrule',
            name='anonymoususer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
