# Generated by Django 2.2.23 on 2021-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0079_auto_20210708_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='legend_position',
            field=models.CharField(choices=[('tab', 'In a separate TAB'), ('toc', 'Into TOC layers')], default='tab', help_text='Set legend position rendering', max_length=20, verbose_name='Legend position rendering'),
        ),
    ]
