# Generated by Django 2.2.23 on 2021-08-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0081_auto_20210819_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['order'], 'permissions': (('add_feature', 'Can add features to layer'), ('change_feature', 'Can update features geometry of layer'), ('delete_feature', 'Can delete features from layer'), ('change_attr_feature', 'Can update features attributes into layer')), 'verbose_name': 'Layer', 'verbose_name_plural': 'Layers'},
        ),
    ]
