# Generated by Django 2.2.23 on 2021-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0082_auto_20210819_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='temporal_properties',
            field=models.TextField(blank=True, null=True, verbose_name='Temporal properties'),
        ),
    ]
