# Generated by Django 2.2.18 on 2022-01-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0083_layer_temporal_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='parent_project',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_project', to='qdjango.Project', verbose_name='Parent Project for Embedded layers'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_name',
            field=models.CharField(default='', editable=False, max_length=256, verbose_name='Qgis project original name'),
        ),
    ]
