# Generated by Django 2.2.18 on 2022-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0086_layer_has_column_acl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='has_column_acl',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Has column ACL constraints'),
        ),
    ]
