# Generated by Django 2.2.18 on 2022-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0087_auto_20220131_0906'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='columnacl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='user_or_group_mutex'),
        ),
        migrations.AddConstraint(
            model_name='columnacl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('group__isnull', True), _connector='OR'), name='user_or_group_is_set'),
        ),
    ]
