# Generated by Django 2.2.26 on 2022-02-09 13:28

from django.db import migrations, models
import django.db.models.deletion
import qdjango.models.column_acl


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0088_auto_20220131_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnacl',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Column level constraint', 'verbose_name_plural': 'Column level constraints'},
        ),
        migrations.AlterField(
            model_name='columnacl',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Layer', validators=[qdjango.models.column_acl.validate_vector]),
        ),
    ]
