# Generated by Django 2.2.26 on 2022-02-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0090_auto_20220209_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['order'], 'permissions': (('add_feature', 'Can add features to layer'), ('change_feature', 'Can update features geometry of layer'), ('delete_feature', 'Can delete features from layer'), ('change_attr_feature', 'Can update features attributes into layer')), 'verbose_name': 'Layer', 'verbose_name_plural': 'Layers'},
        ),
    ]
