# Generated by Django 2.2.27 on 2022-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0092_layeracl'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Fields to se order'),
        )
    ]
