# Generated by Django 2.2.27 on 2022-03-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0093_auto_20220307_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AddConstraint(
            model_name='layeracl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='user_or_group_mutex'),
        ),
        migrations.AddConstraint(
            model_name='layeracl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('group__isnull', True), _connector='OR'), name='user_or_group_is_set'),
        ),
    ]
