# Generated by Django 2.2.27 on 2022-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0094_auto_20220308_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='multilayer_query',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=20, verbose_name='Query control mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='multilayer_querybybbox',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=20, verbose_name='Query by bbox control mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='multilayer_querybypolygon',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=20, verbose_name='Query by polygon control mode'),
        ),
    ]
