# Generated by Django 2.2.27 on 2022-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0095_auto_20220323_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ur_de',
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search'), ('law', 'Law'), ('br_service', 'BR service')], max_length=255, verbose_name='Type'),
        ),
    ]
