# Generated by Django 2.2.27 on 2022-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0097_auto_20220408_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='toc_layers_init_status',
            field=models.CharField(choices=[('collapsed', 'Collapsed'), ('not_collapsed', 'Not collapsed')], default='not_collapsed', help_text="Set tab's TOC layers initials state: 'Collapsed (close)'or 'Not collapsed (open)'", max_length=40, verbose_name="Tab's TOC layer initial status"),
        ),
        migrations.AddField(
            model_name='project',
            name='toc_themes_init_status',
            field=models.CharField(choices=[('collapsed', 'Collapsed'), ('not_collapsed', 'Not collapsed')], default='collapsed', help_text="Set map themes list initials state: 'Collapsed (close)'or 'Not collapsed (open)'", max_length=40, verbose_name='Map themes list initial status'),
        ),
    ]
