# Generated by Django 2.2.28 on 2022-09-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0101_auto_20220830_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('spatialite', 'SpatiaLite'), ('raster', 'Raster'), ('wfs', 'WFS'), ('wms', 'WMS'), ('ogr', 'OGR'), ('gdal', 'GDAL'), ('delimitedtext', 'CSV'), ('arcgismapserver', 'ArcGisMapServer'), ('arcgisfeatureserver', 'ArcGisFeatureServer'), ('mssql', 'MSSQL'), ('virtual', 'VirtualLayer'), ('oracle', 'Oracle'), ('vector-tile', 'Vector Tile'), ('wcs', 'WCS'), ('vectortile', 'Vector Tile'), ('mdal', 'Mesh layer')], max_length=255, verbose_name='Type'),
        ),
    ]
