# Generated by Django 2.2.28 on 2022-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0102_auto_20220928_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoconstraint',
            name='autozoom',
            field=models.BooleanField(default=False, help_text='Active this to make possible auto zoom on geometric constraint (combining every rule) for user on map boostrap', null=True, verbose_name='Autozoom on map boostrap'),
        ),
    ]
