# Generated by Django 2.2.28 on 2023-03-29 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0104_set_is_active_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Set the main title of the message', max_length=400)),
                ('body', models.TextField(help_text='Set the body of the message')),
                ('level', models.PositiveSmallIntegerField(choices=[(20, 'Info'), (30, 'Warning'), (40, 'Error'), (50, 'Critical')], db_index=True, default=20, help_text='Select level of message')),
                ('valid_from', models.DateField(blank=True, help_text='Starting date of message display', null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Ending date of message display', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
