# Generated by Django 2.2.28 on 2023-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0105_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
