# Generated by Django 3.2.19 on 2023-05-11 15:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0106_message_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='columnacl',
            name='user_or_group_mutex',
        ),
        migrations.RemoveConstraint(
            model_name='columnacl',
            name='user_or_group_is_set',
        ),
        migrations.AlterField(
            model_name='widget',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search'), ('law', 'Law')], max_length=255, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='columnacl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='user_or_group_mutex_column'),
        ),
        migrations.AddConstraint(
            model_name='columnacl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('group__isnull', True), _connector='OR'), name='user_or_group_is_set_column'),
        ),
    ]
