# Generated by Django 3.2.19 on 2023-05-16 08:06

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0106_message_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='columnacl',
            name='user_or_group_mutex',
        ),
        migrations.RemoveConstraint(
            model_name='columnacl',
            name='user_or_group_is_set',
        ),
        migrations.AddField(
            model_name='message',
            name='body_de',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_en',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_fi',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_fr',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_it',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_ro',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_se',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_de',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_en',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_fi',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_fr',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_it',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_ro',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_se',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='columnacl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='user_or_group_mutex_column'),
        ),
        migrations.AddConstraint(
            model_name='columnacl',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', True), ('group__isnull', True), _connector='OR'), name='user_or_group_is_set_column'),
        ),
    ]
