# Generated by Django 3.2.19 on 2023-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0107_auto_20230511_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search')], max_length=255, verbose_name='Type'),
        ),
    ]
