# Generated by Django 3.2.19 on 2023-06-13 12:11

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0107_auto_20230516_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
    ]
