# Generated by Django 3.2.19 on 2023-07-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0108_alter_layer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wms_getmap_format',
            field=models.CharField(blank=False, choices=[('image/png; mode=8bit', 'PNG 8bit Format'), ('image/png; mode=16bit', 'PNG 16bit Format'), ('image/png', 'PNG format'), ('image/jpeg', 'JPEG format')], default='image/png; mode=8bit', max_length=255, null=True, verbose_name='WMS GetMap image format'),
        ),
    ]
