# Generated by Django 3.2.20 on 2023-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0109_project_wms_getmap_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontokenfilterlayer',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
