# Generated by Django 3.2.20 on 2023-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0110_sessiontokenfilterlayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontokenfilterlayer',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
