# Generated by Django 3.2.20 on 2023-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0111_alter_sessiontokenfilterlayer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontokenfilterlayer',
            name='name',
        ),
        migrations.AddField(
            model_name='filterlayersaved',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
