# Generated by Django 3.2.23 on 2023-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0113_auto_20231019_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontokenfilter',
            name='token',
            field=models.CharField(max_length=65),
        ),
    ]
