# Generated by Django 3.2.23 on 2023-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0114_alter_sessiontokenfilter_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geocoding_providers',
            field=models.TextField(blank=True, null=True, verbose_name='Geocoding providers'),
        ),
    ]
