# Generated by Django 3.2.23 on 2023-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0115_alter_layer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geocoding_providers',
            field=models.TextField(blank=True, null=True, verbose_name='Geocoding providers'),
        ),

        # Rename map control nominatim in geocoding
        migrations.RunSQL(
            "UPDATE core_mapcontrol SET name='geocoding' WHERE name='nominatim'"
        ),
        migrations.RunSQL(
            "UPDATE qdjango_project SET geocoding_providers='[\"nominatim\"]'"
        ),
    ]
