# Generated by Django 3.2.23 on 2023-12-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0115_project_geocoding_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='toc_layers_init_status',
            field=models.CharField(choices=[('collapsed', 'Collapsed'), ('not_collapsed', 'Not collapsed')], default='not_collapsed', help_text="Set tab's TOC layers initials state: 'Collapsed (close)' or 'Not collapsed (open)'", max_length=40, verbose_name="Tab's TOC layer initial status"),
        ),
        migrations.AlterField(
            model_name='project',
            name='toc_themes_init_status',
            field=models.CharField(choices=[('collapsed', 'Collapsed'), ('not_collapsed', 'Not collapsed')], default='collapsed', help_text="Set map themes list initials state: 'Collapsed (close)' or 'Not collapsed (open)'", max_length=40, verbose_name='Map themes list initial status'),
        ),
    ]
