# Generated by Django 3.2.25 on 2024-04-16 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qdjango', '0116_auto_20231204_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='use_map_extent_as_init_extent',
            field=models.BooleanField(default=False, verbose_name='Use QGIS project map start extent as webgis init extent'),
        ),
        migrations.CreateModel(
            name='CustomerTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Theme name')),
                ('theme', models.TextField(verbose_name='JSON theme structure')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
