# Generated by Django 3.2.24 on 2024-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0116_auto_20231204_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_pl',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_pl',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_map_extent_as_init_extent',
            field=models.BooleanField(default=False, verbose_name='Use QGIS project map start extent as webgis init extent'),
        ),
    ]
