# Generated by Django 3.2.25 on 2024-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0117_auto_20240416_0757'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customertheme',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'name'), name='unique_name_user'),
        ),
    ]
