# Generated by Django 3.2.25 on 2024-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0118_customertheme_unique_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='exclude_from_toc',
            field=models.BooleanField(blank=True, default=False, verbose_name='Exclude to TOC'),
        ),
    ]
