# Generated by Django 3.2.25 on 2024-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0119_layer_exclude_from_toc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='exclude_from_toc',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Exclude to TOC'),
        ),
    ]
