# Generated by Django 3.2.25 on 2024-05-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0120_alter_layer_exclude_from_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='download_pdf',
            field=models.BooleanField(blank=True, default=False, verbose_name='Download single attributes row in pdf format'),
        ),
    ]
