# Generated by Django 3.2.25 on 2024-06-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0121_layer_download_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='origname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Original Name'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='qgs_layer_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Qgis Layer Project ID'),
        ),
    ]
