# Generated by Django 4.2.18 on 2025-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0122_auto_20240604_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='message',
            name='body_pt',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_pt',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
    ]
