# Generated by Django 4.2.18 on 2025-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0122_auto_20240604_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='project',
            name='show_metadata_section',
            field=models.BooleanField(default=True, help_text="If possibile shoose is show or hide the 'Metadata' section on left bar", verbose_name="Show the 'Metadata' section on left bar"),
        ),
    ]
