# Generated by Django 4.2.18 on 2025-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0122_auto_20240604_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_ar',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_ar',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('search', 'Search')], max_length=255, verbose_name='Type'),
        ),
    ]
