# Generated by Django 4.2.18 on 2025-05-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0123_alter_message_options_project_show_metadata_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='show_metadata_section',
            field=models.BooleanField(default=True, help_text="It is possible choose if show or hide the 'Metadata' section on left bar", verbose_name="Show the 'Metadata' section on left bar"),
        ),
    ]
