# Generated by Django 4.2.18 on 2025-05-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('qdjango', '0124_layer_info_result_number_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleVisibilityLayerConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymoususer', models.BooleanField(blank=True, default=False, null=True)),
                ('minscale', models.IntegerField(blank=True, null=True)),
                ('maxscale', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_visibility_layer', to='qdjango.layer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scale visibility layer constraint',
                'verbose_name_plural': 'Scale visibility layer constraints',
            },
        ),
    ]
