# Generated by Django 4.2.18 on 2025-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0125_scalevisibilitylayerconstraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scalevisibilitylayerconstraint',
            constraint=models.UniqueConstraint(fields=('layer', 'user'), name='layer-user-unique'),
        ),
        migrations.AddConstraint(
            model_name='scalevisibilitylayerconstraint',
            constraint=models.UniqueConstraint(fields=('layer', 'group'), name='layer-group-unique'),
        ),
    ]
