# Generated by Django 4.2.18 on 2025-05-15 09:19

from django.db import migrations, models
import django.db.models.deletion
import qdjango.models.column_acl


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0126_scalevisibilitylayerconstraint_layer_user_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scalevisibilitylayerconstraint',
            options={'ordering': ['-pk'], 'verbose_name': 'Scale visibility layer constraint', 'verbose_name_plural': 'Scale visibility layer constraints'},
        ),
        migrations.RemoveField(
            model_name='scalevisibilitylayerconstraint',
            name='anonymoususer',
        ),
        migrations.AlterField(
            model_name='scalevisibilitylayerconstraint',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_visibility_layer', to='qdjango.layer', validators=[qdjango.models.column_acl.validate_vector]),
        ),
    ]
