# Generated by Django 4.2.22 on 2025-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0127_alter_scalevisibilitylayerconstraint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='max_scale_style',
            field=models.TextField(blank=True, null=True, verbose_name='Layer Max Scale visibility for layer styel'),
        ),
        migrations.AddField(
            model_name='layer',
            name='min_scale_style',
            field=models.TextField(blank=True, null=True, verbose_name='Layer Max Scale visibility for layer styel'),
        ),
    ]
