# Generated by Django 4.2.22 on 2025-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0128_layer_max_scale_style_layer_min_scale_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='max_scale_style',
            field=models.JSONField(blank=True, null=True, verbose_name='Layer Max Scale visibility for layer styel'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='min_scale_style',
            field=models.JSONField(blank=True, null=True, verbose_name='Layer Max Scale visibility for layer styel'),
        ),
    ]
