# Generated by Django 4.2.22 on 2025-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0129_alter_layer_max_scale_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='scalebasedvisibility_style',
            field=models.JSONField(blank=True, null=True, verbose_name='Scale based visibility for layer style'),
        ),
    ]
