# Generated by Django 4.2.21 on 2025-07-06 22:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0130_layer_scalebasedvisibility_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='slug',
            field=core.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=core.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='slug',
            field=core.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='Slug'),
        ),
    ]
