# Generated by Django 4.2.21 on 2025-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0131_alter_layer_slug_alter_project_slug_and_more'),
        ('core', '0093_i18n_bulgarian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='message',
            name='body_bg',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_bg',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_bg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
    ]
