# Generated by Django 4.2.22 on 2025-08-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0132_i18n_bulgarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sidebar_collapse',
            field=models.BooleanField(default=False, help_text='Choose if the left sidebar is collapsed on start of webgis', verbose_name='Start left sidebar collapsed'),
        ),
    ]
