# Generated by Django 4.2.27 on 2026-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0135_message_body_pt_message_title_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='toc_tab_default',
            field=models.CharField(choices=[('layers', 'Layers'), ('legend', 'Legend')], default='layers', help_text="Set tab's TOC open by default on init client", max_length=40, verbose_name="Tab's TOC active as default"),
        ),
        migrations.AlterField(
            model_name='project',
            name='wms_getmap_format',
            field=models.CharField(choices=[('image/png; mode=1bit', 'PNG 1bit'), ('image/png; mode=8bit', 'PNG 8bit'), ('image/png; mode=16bit', 'PNG 16bit'), ('image/png', 'PNG'), ('image/jpeg', 'JPEG'), ('image/webp', 'WEBP')], default='image/png', max_length=255, null=True, verbose_name='WMS GetMap image format'),
        ),
    ]
