# Generated by Django 4.2.27 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0133_project_sidebar_collapse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='autozoom_query',
            field=models.BooleanField(default=True, help_text='Automatic zoom on query result features for only one layer', verbose_name='Automatic zoom to query result features'),
        ),
        migrations.AlterField(
            model_name='project',
            name='show_metadata_section',
            field=models.BooleanField(default=False, help_text="It is possible choose if show or hide the 'Metadata' section on left bar", verbose_name="Show the 'Metadata' section on left bar"),
        ),
    ]
