# Generated by Django 4.2.29 on 2026-04-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0134_projectbookmark'),
        ('qdjango', '0135_message_body_pt_message_title_pt_and_more'),
        ('qdjango', '0136_alter_project_toc_tab_default_and_more'),
        ('qdjango', '0137_alter_project_autozoom_query_and_more'),
        ('qdjango', '0138_columnacl_multi_users_groups'),
    ]

    operations = [
    ]
