# Generated by Django 4.2.30 on 2026-05-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0139_merge_20260407_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_es',
            field=models.TextField(help_text='Set the body of the message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title_es',
            field=models.CharField(help_text='Set the main title of the message', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ur_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public title'),
        ),
    ]
