# Generated by Django 4.2.30 on 2026-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0140_message_body_es_message_title_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='srid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project SRID'),
        ),
    ]
