# Generated by Django 4.2.30 on 2026-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0140_message_body_es_message_title_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='wmtscapabilities',
            field=models.JSONField(blank=True, null=True, verbose_name='Dict wmts options'),
        ),
    ]
