# Generated by Django 4.2.30 on 2026-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0141_layer_wmtscapabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wmts_grids',
            field=models.TextField(blank=True, null=True, verbose_name='WMTS grids'),
        ),
    ]
