# Generated by Django 4.2.30 on 2026-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0142_project_wmts_grids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wmts_grids',
            field=models.JSONField(blank=True, null=True, verbose_name='WMTS grids'),
        ),
    ]
