# Generated by Django 4.2.30 on 2026-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0143_alter_project_wmts_grids'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='wmts_format',
            field=models.CharField(blank=True, choices=[('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, null=True, verbose_name='Render layer as WMTS'),
        ),
    ]
