# Generated by Django 4.2.30 on 2026-10-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0141_project_srid'),
        ('qdjango', '0144_layer_wmts_format'),
    ]

    operations = [
    ]
