# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from=b'name', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
