# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogc', '0003_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('wms', 'WMS'), ('wmst', 'wmst'), ('WMST', 'WMST'), ('tms', 'TMS')], max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('wms', 'WMS'), ('wmst', 'wmst'), ('WMST', 'WMST'), ('wfs', 'WFS')], max_length=20, verbose_name='OGC Type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
