# Generated by Django 2.2.23 on 2021-11-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0082_auto_20210819_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRasterTimeSeriesProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrastertimeseries_projects', to='qdjango.Project')),
            ],
            options={
                'verbose_name': 'QRasterTimeSeries Project',
            },
        ),
        migrations.CreateModel(
            name='QRasterTimeSeriesLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('layer', models.ForeignKey(help_text='Select NETCDF raster project layer to use', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrastertimeseries_layer', to='qdjango.Layer')),
                ('qrastertimeseries_project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrastertimeseries_project', to='qrastertimeseries.QRasterTimeSeriesProject')),
            ],
            options={
                'verbose_name': 'QRasterTimeSeries vector Layer',
            },
        ),
    ]
