# Generated by Django 2.2.13 on 2020-09-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0052_layer_download_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qgs_layer_id', models.CharField(max_length=400, verbose_name='QGIS project layer id')),
                ('selected_features_only', models.BooleanField(default=False, verbose_name='Use selected features only')),
                ('visible_features_only', models.BooleanField(default=False, verbose_name='Use visible features only')),
                ('xml', models.TextField(verbose_name='XML original settings')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdjango.Project')),
            ],
        ),
    ]
