# Generated by Django 2.2.13 on 2020-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qplotlywidget',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Plot type'),
        ),
    ]
