# Generated by Django 2.2.13 on 2020-09-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qplotly_setting', to='qdjango.Project'),
        ),
    ]
