# Generated by Django 2.2.13 on 2020-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0002_qplotlywidget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qplotlywidget',
            name='datasource',
            field=models.TextField(null=True, verbose_name='Layer datasource'),
        ),
    ]
