# Generated by Django 2.2.13 on 2020-09-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0052_layer_download_csv'),
        ('qplotly', '0003_auto_20200925_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='qplotlywidget',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qdjango.Project'),
        ),
        migrations.AddField(
            model_name='qplotlywidget',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Plot title'),
        ),
    ]
