# Generated by Django 2.2.16 on 2021-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0004_auto_20200925_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='qplotlywidget',
            name='show_on_start_client',
            field=models.BooleanField(default=False, null=True, verbose_name='Set as default plot on starting map'),
        ),
    ]
