# Generated by Django 4.2.18 on 2025-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0005_qplotlywidget_show_on_start_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qplotlywidget',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='qplotlywidget',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
