# Generated by Django 4.2.18 on 2025-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0006_alter_qplotlywidget_options_qplotlywidget_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qplotlywidget',
            options={},
        ),
        migrations.AlterField(
            model_name='qplotlywidget',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Fields order'),
        ),
    ]
