# Generated by Django 4.2.18 on 2025-05-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0007_alter_qplotlywidget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qplotlywidget',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Order'),
        ),
    ]
