# Generated by Django 4.2.22 on 2025-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0008_alter_qplotlywidget_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='qplotlywidget',
            name='show_in_sidebar',
            field=models.BooleanField(default=True, help_text='Show this plot in the sidebar. If not checked, it will be shown only on results of a query.', verbose_name='Show in sidebar'),
        ),
    ]
