# Generated by Django 4.2.22 on 2025-06-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0009_qplotlywidget_show_in_sidebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qplotlywidget',
            name='show_in_sidebar',
        ),
        migrations.AddField(
            model_name='qplotlywidget',
            name='show_poistion',
            field=models.CharField(blank=True, default='sidebarquery', max_length=100, null=True, verbose_name='SChart show position'),
        ),
    ]
