# Generated by Django 4.2.22 on 2025-06-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0010_remove_qplotlywidget_show_in_sidebar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qplotlywidget',
            old_name='show_poistion',
            new_name='show_position',
        ),
    ]
