# Generated by Django 4.2.27 on 2026-03-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0011_rename_show_poistion_qplotlywidget_show_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='QplotlyWidgetRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_relations', to='qplotly.qplotlywidget', verbose_name='Source widget')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_related_by', to='qplotly.qplotlywidget', verbose_name='Target widget')),
            ],
            options={
                'verbose_name': 'QPlotly Widget relation',
                'verbose_name_plural': 'QPlotly Widget relations',
                'ordering': ['order'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.AddField(
            model_name='qplotlywidget',
            name='related_widgets',
            field=models.ManyToManyField(blank=True, related_name='associated_by', through='qplotly.QplotlyWidgetRelation', to='qplotly.qplotlywidget', verbose_name='Related widgets'),
        ),
    ]
