# Generated by Django 4.2.27 on 2026-03-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0012_qplotlywidgetrelation_qplotlywidget_related_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qplotlywidgetrelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='widget_relations', to='qplotly.qplotlywidget', verbose_name='Source widget'),
        ),
        migrations.AlterField(
            model_name='qplotlywidgetrelation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='widget_related_by', to='qplotly.qplotlywidget', verbose_name='Target widget'),
        ),
    ]
