# Generated by Django 4.2.27 on 2026-03-18 00:00

from django.db import migrations, models
import django.db.models.deletion


def fill_relation_project(apps, schema_editor):
    QplotlyWidgetRelation = apps.get_model('qplotly', 'QplotlyWidgetRelation')

    for relation in QplotlyWidgetRelation.objects.select_related('source', 'target').all().iterator():
        project_id = relation.source.project_id or relation.target.project_id
        if relation.project_id != project_id:
            relation.project_id = project_id
            relation.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0014_alter_qplotlywidgetrelation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qplotlywidgetrelation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qplotly_widget_relations', to='qdjango.project', verbose_name='Project'),
        ),
        migrations.RunPython(fill_relation_project, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='qplotlywidgetrelation',
            unique_together={('project', 'source', 'target')},
        ),
    ]
