# Generated by Django 4.2.27 on 2026-03-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qplotly', '0015_qplotlywidgetrelation_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qplotlywidget',
            name='project',
        ),
    ]
