# Generated by Django 2.2.16 on 2021-03-30 15:27

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0073_project_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenrouteserviceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Isochrones')], max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openrouteservice_projects', to='qdjango.Project')),
            ],
            options={
                'verbose_name': 'Openrouteservice Project',
            },
        ),
    ]
