# Generated by Django 2.2.16 on 2021-03-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openrouteservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openrouteserviceproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openrouteservice_projects', to='qdjango.Project'),
        ),
    ]
