# Generated by Django 2.2.16 on 2021-03-30 17:10

from django.db import migrations
import multiselectfield.db.fields
import openrouteservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('openrouteservice', '0002_auto_20210330_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openrouteserviceproject',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(openrouteservice.models.OpenrouteserviceService(1), 'Isochrones')], max_length=12),
        ),
    ]
