# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legclslrg',
            options={'verbose_name': 'Legenda CLS_LRG tabella archi', 'verbose_name_plural': 'Legenda CLS_LRG tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legclstcn',
            options={'verbose_name': 'Legenda CLS_TCN tabella archi', 'verbose_name_plural': 'Legenda CLS_TCN tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legcmpele',
            options={'verbose_name': 'Legenda CMP_ELE tabella archi', 'verbose_name_plural': 'Legenda CMP_ELE tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legcoddug',
            options={'verbose_name': 'Legenda COD_DUG tabella toponimo', 'verbose_name_plural': 'Legenda COD_DUG tabella toponimo'},
        ),
        migrations.AlterModelOptions(
            name='legcodsed',
            options={'verbose_name': 'Legenda COD_SED tabella archi', 'verbose_name_plural': 'Legenda COD_SED tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legcodsta',
            options={'verbose_name': 'Legenda COD_STA tabella archi', 'verbose_name_plural': 'Legenda COD_STA tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legorg',
            options={'verbose_name': 'Legenda ORG tabella archi', 'verbose_name_plural': 'Legenda ORG tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legsotpas',
            options={'verbose_name': 'Legenda SOT_PAS tabella archi', 'verbose_name_plural': 'Legenda SOT_PAS tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legtipacc',
            options={'verbose_name': 'Legenda TIP_ACC tabella accessi', 'verbose_name_plural': 'Legenda TIP_ACC tabella accessi'},
        ),
        migrations.AlterModelOptions(
            name='legtipele',
            options={'verbose_name': 'Legenda TIP_ELE tabella archi', 'verbose_name_plural': 'Legenda TIP_ELE tabella archi'},
        ),
        migrations.AlterModelOptions(
            name='legtipgnz',
            options={'verbose_name': 'Legenda TIP_GNZ tabella nodi', 'verbose_name_plural': 'Legenda TIP_GNZ tabella nodi'},
        ),
        migrations.AlterModelOptions(
            name='legtipgst',
            options={'verbose_name': 'Legenda TIP_GST tabella archi', 'verbose_name_plural': 'Legenda TIP_GST tabella archi'},
        ),
        migrations.AlterField(
            model_name='accessi',
            name='tip_acc',
            field=models.ForeignKey(blank=True, db_column='tip_acc', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegTipAcc'),
        ),
    ]
