# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0002_auto_20160330_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archi',
            name='cls_lrg',
            field=models.ForeignKey(blank=True, db_column='cls_lrg', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegClsLrg'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='cls_tcn',
            field=models.ForeignKey(blank=True, db_column='cls_tcn', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegClsTcn'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='cmp_ele',
            field=models.ForeignKey(blank=True, db_column='cmp_ele', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegCmpEle'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='cod_sed',
            field=models.ForeignKey(blank=True, db_column='cod_sed', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegCodSed'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='cod_sta',
            field=models.ForeignKey(blank=True, db_column='cod_sta', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegCodSta'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='org',
            field=models.ForeignKey(blank=True, db_column='org', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegOrg'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='sot_pas',
            field=models.ForeignKey(blank=True, db_column='sot_pas', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegSotPas'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='tip_ele',
            field=models.ForeignKey(blank=True, db_column='tip_ele', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegTipEle'),
        ),
        migrations.AlterField(
            model_name='archi',
            name='tip_gst',
            field=models.ForeignKey(blank=True, db_column='tip_gst', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegTipGst'),
        ),
    ]
