# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0003_auto_20160330_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessi',
            options={'verbose_name': 'Accesso', 'verbose_name_plural': 'Accessi'},
        ),
        migrations.AlterModelOptions(
            name='archi',
            options={'verbose_name': 'Arco', 'verbose_name_plural': 'Archi'},
        ),
        migrations.AlterModelOptions(
            name='civici',
            options={'verbose_name': 'Civico', 'verbose_name_plural': 'Civici'},
        ),
        migrations.AlterModelOptions(
            name='nodi',
            options={'verbose_name': 'Nodo', 'verbose_name_plural': 'Nodi'},
        ),
        migrations.AlterModelOptions(
            name='toponimo',
            options={'verbose_name': 'Toponimo', 'verbose_name_plural': 'Toponimi'},
        ),
        migrations.AlterField(
            model_name='nodi',
            name='org',
            field=models.ForeignKey(blank=True, db_column='org', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegOrg'),
        ),
        migrations.AlterField(
            model_name='nodi',
            name='tip_gnz',
            field=models.ForeignKey(blank=True, db_column='tip_gnz', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegTipGnz'),
        ),
    ]
