# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0004_auto_20160330_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegCodDug',
            new_name='LegDug',
        ),
        migrations.RenameField(
            model_name='toponimo',
            old_name='cod_dug',
            new_name='dug',
        ),
    ]
