# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0005_auto_20160331_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legdug',
            options={'verbose_name': 'Legenda COD_DUG tabella toponimo', 'verbose_name_plural': 'Legenda DUG tabella toponimo'},
        ),
        migrations.AlterField(
            model_name='toponimo',
            name='dug',
            field=models.ForeignKey(blank=True, db_column='dug', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegDug'),
        ),
    ]
