# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0006_auto_20160331_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='toponimo',
            name='cod_top2',
            field=models.CharField(default=None, max_length=15, primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toponimo',
            name='cod_top',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
