# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0007_auto_20160331_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toponimostradale',
            options={'verbose_name': 'Toponimo stradale', 'verbose_name_plural': 'Toponimi stradali'},
        ),
    ]
