# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0008_auto_20160331_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ele_old', models.CharField(blank=True, max_length=15, null=True)),
                ('tip_opz', models.CharField(blank=True, choices=[('U', 'aggiornato'), ('D', 'cancellato'), ('S', 'sostituito'), ('I', 'nuovo inserimento')], max_length=1, null=True)),
                ('cod_ele_new', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'archi_info',
                'verbose_name': 'Archi info',
                'verbose_name_plural': 'Archi info',
            },
        ),
        migrations.CreateModel(
            name='ToponimiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_top', models.CharField(blank=True, max_length=15, null=True)),
                ('tip_opz', models.CharField(blank=True, choices=[('U', 'update'), ('I', 'insert'), ('D', 'delete')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'toponimi_info',
                'verbose_name': 'Toponimi info',
                'verbose_name_plural': 'Toponimi info',
            },
        ),
        migrations.DeleteModel(
            name='CiviciInfo',
        ),
    ]
