# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0009_auto_20160331_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiviciInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_civ', models.CharField(blank=True, max_length=16, null=True)),
                ('tip_opz', models.CharField(blank=True, choices=[('U', 'update'), ('I', 'insert'), ('D', 'delete')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'civici_info',
                'verbose_name': 'Civici info',
                'verbose_name_plural': 'Civici info',
            },
        ),
    ]
