# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0011_auto_20160331_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_gnz', models.CharField(blank=True, max_length=15, null=True)),
                ('tip_opz', models.CharField(blank=True, choices=[('U', 'aggiornato'), ('I', 'nuovo inserimento'), ('D', 'cancellato')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'nodi_info',
                'verbose_name': 'Accessi info',
                'verbose_name_plural': 'Accessi info',
            },
        ),
    ]
