# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0012_nodiinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legtippav',
            options={'verbose_name': 'Legenda TIP_PAV tabella elemento stradale', 'verbose_name_plural': 'Legenda TIP_PAV tabella elemento stradale'},
        ),
    ]
