# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0016_auto_20160401_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='qdjango_project',
            new_name='project',
        ),
    ]
