# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0017_auto_20160401_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementostradale',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=3003),
        ),
    ]
