# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0018_auto_20160408_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementostradale',
            name='cod_gst',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
