# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0019_auto_20160413_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legcoddug',
            options={'verbose_name': 'Legenda COD_DUG tabella toponimo stradale', 'verbose_name_plural': 'Legenda COD_DUG tabella toponimo stradale'},
        ),
        migrations.AlterModelOptions(
            name='nodiinfo',
            options={'verbose_name': 'Nodi info', 'verbose_name_plural': 'Nodi info'},
        ),
        migrations.AlterField(
            model_name='toponimostradale',
            name='cod_dug',
            field=models.ForeignKey(blank=True, db_column='cod_dug', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegCodDug'),
        ),
    ]
