# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import iternet.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0021_auto_20160414_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegPasCar',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leg_pas_car',
                'verbose_name': 'Legenda PAS_CAR tabella accesso',
                'verbose_name_plural': 'Legenda PAS_CAR tabella accesso',
            },
            bases=(iternet.mixins.models.LegIternetModelMixin, models.Model),
        ),
    ]
