# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0022_legpascar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesso',
            name='pas_car',
            field=models.ForeignKey(blank=True, db_column='pas_car', null=True, on_delete=django.db.models.deletion.CASCADE, to='iternet.LegPasCar'),
        ),
    ]
