# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0025_auto_20160415_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuni',
            options={'verbose_name': 'Comune', 'verbose_name_plural': 'Comuni provinciali'},
        ),
        migrations.AlterField(
            model_name='toponimostradale',
            name='cod_com',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
