# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0027_comuni_cod_istat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessiinfo',
            name='cod_acc',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
