# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0028_auto_20160418_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesso',
            name='cod_ele',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
