# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0031_auto_20160423_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesso',
            name='cod_acc',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
