# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0032_auto_20160423_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementostradale',
            name='cmp_ele',
            field=models.ForeignKey(db_column='cmp_ele', on_delete=django.db.models.deletion.CASCADE, to='iternet.LegCmpEle'),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='cod_gst',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='cod_top',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='lng',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='nod_fin',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='nod_ini',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='sot_pas',
            field=models.ForeignKey(db_column='sot_pas', on_delete=django.db.models.deletion.CASCADE, to='iternet.LegSotPas'),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='tip_ele',
            field=models.ForeignKey(db_column='tip_ele', on_delete=django.db.models.deletion.CASCADE, to='iternet.LegTipEle'),
        ),
        migrations.AlterField(
            model_name='elementostradale',
            name='tip_gst',
            field=models.ForeignKey(db_column='tip_gst', on_delete=django.db.models.deletion.CASCADE, to='iternet.LegTipGst'),
        ),
    ]
