# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iternet', '0033_auto_20160423_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toponimostradale',
            name='cod_com',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='toponimostradale',
            name='cod_dug',
            field=models.ForeignKey(db_column='cod_dug', on_delete=django.db.models.deletion.CASCADE, to='iternet.LegCodDug'),
        ),
        migrations.AlterField(
            model_name='toponimostradale',
            name='den_uff',
            field=models.CharField(max_length=100),
        ),
    ]
