# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caching', '0002_g3wcachinglayer_tilestache_layer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g3wcachinglayer',
            name='tilestache_layer_name',
        ),
    ]
