# Generated by Django 2.2.13 on 2020-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caching', '0003_remove_g3wcachinglayer_tilestache_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='g3wcachinglayer',
            name='baselayer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
