name: Test deploy static files (dev.g3wsuite.it)
on:
  push:
    branches:
      - '**'
    paths:
      - '**/static/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: pip install playwright

      - name: Install Playwright browser
        run: playwright install chromium

      - name: Run tests
        run: python ci_scripts/test/dev.g3wsuite.it.py